[package]
name = "rarity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
# name = "rarity"

[dependencies]
extendr-api = "0.6.0"
rayon = "1.10.0"
# lmutils = { version = "0.1", path = "../../../../lmutils" }
lmutils = "0.1"
