# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rarity_wrappers", use_symbols = TRUE, package_name = "rarity")

#' @docType package
#' @usage NULL
#' @useDynLib rarity, .registration = TRUE
NULL

#' Run a RARity analysis.
#' `dir` is the directory where the data is stored.
#' `pheno_file` is a character vector of normalized phenotype file names, relative to `dir`.
#' for chromosome `i`.
#' Returns a data frame with the results.
#' @export
rarity <- function(dir, phenos) .Call(wrap__rarity, dir, phenos)

#' Set the log level.
#' `level` is the log level.
#' @export
set_log_level <- function(level) invisible(.Call(wrap__set_log_level, level))

#' Set the number of blocks per chunk.
#' `blocks_per_chunk` is the number of blocks per chunk.
#' @export
set_blocks_per_chunk <- function(blocks_per_chunk) invisible(.Call(wrap__set_blocks_per_chunk, blocks_per_chunk))

#' Set the number of threads.
#' `num_threads` is the number of threads.
#' @export
set_num_threads <- function(num_threads) invisible(.Call(wrap__set_num_threads, num_threads))

#' Set the min sum for the RARity analysis.
#' `min_sum` is the min sum.
#' @export
set_min_sum <- function(min_sum) invisible(.Call(wrap__set_min_sum, min_sum))


# nolint end
