# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rarity_wrappers", use_symbols = TRUE, package_name = "rarity")

#' @docType package
#' @usage NULL
#' @useDynLib rarity, .registration = TRUE
NULL

#' Run a RARity analysis.
#' `dir` is the directory where the data is stored.
#' `pheno_file` is a character vector of normalized phenotype file names, relative to `dir`.
#' `genes` is a list of character vectors, with the vector at index `i` containing the gene names
#' for chromosome `i`.
#' Returns a data frame with the results.
#' @export
rarity <- function(dir, phenos, genes) .Call(wrap__rarity, dir, phenos, genes)


# nolint end
